query GetTransactions ($orderBy: TransactionOrderByEnum) {
    transactions (orderBy: $orderBy) {
        id
        insertedAt
        user {
            id
            firstName
            lastName
        }
        category {
            id
            name
        }
        company {
            id
            name
        }
        description
        merchant {
            id
            name
        }
        debit
        credit
        amount
    }
}
