query GetTransactions ($orderBy: TransactionOrderByEnum) {
    transactions (orderBy: $orderBy) {
        id
        insertedAt
        user {
            firstName
            lastName
        }
        category {
            name
        }
        description
        merchant {
            name
        }
        debit
        credit
        amount
    }
}
